version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - network

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-service
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: ""
      PORT: 8080
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
    driver: bridge
