version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  cache:
    image: redis:6.2
    container_name: cache
    ports:
      - "6379:6379"

networks:
  default:
    name: forum-net
    driver: bridge
